# Generated by Django 4.2.7 on 2023-11-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Размер контейнера')),
                ('available', models.BooleanField(blank=True, choices=[(True, 'Свободен'), (False, 'Занят')], null=True, verbose_name='Свободен ли контейнер')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Когда контейнер был занят')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Когда контейнер освободится')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='storage.customer', verbose_name='Кем занят')),
            ],
        ),
    ]
