# Generated by Django 4.2.7 on 2023-11-15 11:51

from django.db import migrations
from random import choice


def create_containers(apps, schema_editor):
    Container = apps.get_model('storage', 'Container')
    for _ in range(100):
        Container.objects.create(
            size=choice(['Маленький', 'Средний', 'Большой']),
            available=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_item_container_filled_by'),
    ]

    operations = [
        migrations.RunPython(create_containers)
    ]
