# Generated by Django 4.2.7 on 2023-11-15 12:12

from django.db import migrations
from random import choice


def remove_containers(apps, schema_editor):
    Container = apps.get_model('storage', 'Container')
    Container.objects.all().delete()


def create_containers(apps, schema_editor):
    Container = apps.get_model('storage', 'Container')
    for _ in range(100):
        Container.objects.create(
            size=choice(
                [
                    'Локер',
                    'Низкий',
                    'Антресольный',
                    'Стандартный',
                    'Большой',
                    'Безразмерный'

                ]
            ),
            available=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20231115_1451'),
    ]

    operations = [
        migrations.RunPython(remove_containers),
        migrations.RunPython(create_containers)
    ]
