# Generated by Django 4.2.7 on 2023-11-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20231115_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало срока хранения')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание срока хранения')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес склада')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='storage.customer', verbose_name='Кем был сделан заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название шага')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения в шаге')),
            ],
        ),
        migrations.RemoveField(
            model_name='container',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='container',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='container',
            name='filled_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Чем заполнен'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='button',
            name='step',
            field=models.ManyToManyField(blank=True, related_name='buttons', to='storage.step', verbose_name='Прикрепленный шаг'),
        ),
        migrations.AddField(
            model_name='container',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='storage.delivery', verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='container',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='storage.reservation', verbose_name='Заказ'),
        ),
    ]
