# Generated by Django 4.2.7 on 2023-11-16 14:52

from django.db import migrations


def fill_up_steps(apps, schema_editor):
    Step = apps.get_model('storage', 'Step')
    steps = [
        {
            "name": "Дата приезда",
            "text": """Укажите дату вашего приезда на склад"""
        }
    ]
    for step in steps:
        Step.objects.create(
            name=step['name'],
            text=step['text']
        )



class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20231116_1731'),
    ]

    operations = [
        migrations.RunPython(fill_up_steps)
    ]
