# Generated by Django 4.2.7 on 2023-11-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20231116_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='storage.step', verbose_name='Связь между шагами'),
        ),
    ]
