# Generated by Django 4.2.7 on 2023-11-17 11:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_button_step_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Нормализованный Номер владельца'),
        ),
    ]
