# Generated by Django 4.2.7 on 2023-11-17 11:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_customer_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный Номер владельца'),
        ),
    ]
