# Generated by Django 4.2.7 on 2023-11-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_alter_customer_pure_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_bot',
            field=models.BooleanField(blank=True, null=True, verbose_name='Бот или нет'),
        ),
        migrations.AddField(
            model_name='customer',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код языка'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента 3'),
        ),
    ]
