# Generated by Django 4.2.7 on 2023-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_rename_first_name_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='next_step',
            field=models.ManyToManyField(blank=True, related_name='prev_buttons', to='storage.step', verbose_name='На какой шаг перейти'),
        ),
    ]
