# Generated by Django 4.2.7 on 2023-11-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_button_next_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='self_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента 4'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id клиента'),
        ),
    ]
