# Generated by Django 4.2.7 on 2023-11-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_button_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='next_step',
        ),
        migrations.AddField(
            model_name='button',
            name='next_step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.step', verbose_name='На какой шаг перейти'),
        ),
    ]
