# Generated by Django 4.2.7 on 2023-11-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_remove_button_next_step_button_next_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_button', to='storage.step', verbose_name='На какой шаг перейти'),
        ),
    ]
