# Generated by Django 4.2.7 on 2023-11-18 07:13

from django.db import migrations


def add_next_step_to_buttons(apps, schema_editor):
    Button = apps.get_model('storage', 'Button')
    Step = apps.get_model('storage', 'Step')
    buttons = [
        {
            "step": "Контакты",
            "text": "Контакты",
        },
        {
            "step": "Способ складирования",
            "text": "Выбрать бокс",
        },
        {
            "step": "Правила аренды",
            "text": "Правила размещения",
        },
        {
            "step": "Выбор боксов 1",
            "text": "Своими силами",
        },
        {
            "step": "Выбор бокса 2",
            "text": "Бесплатная доставка из дома",
        },
        {
            "step": "Срок аренды",
            "text": "1",
        },
        {
            "step": "Срок аренды",
            "text": "2",
        },
        {
            "step": "Срок аренды",
            "text": "3",
        }
    ]
    for button in buttons:
        step = Step.objects.get(name=button['step'])

        new_button = Button.objects.get(
            text=button['text']
        )

        new_button.next_step = step
        new_button.save()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_alter_button_next_step'),
    ]

    operations = [
        migrations.RunPython(add_next_step_to_buttons)
    ]
