# Generated by Django 4.2.7 on 2023-11-18 08:09

from django.db import migrations


def add_order_to_buttons(apps, schema_editor):
    Button = apps.get_model('storage', 'Button')
    buttons = [
        {
            "text": "Правила размещения",
            "order": 10,
        },
        {
            "text": "Контакты",
            "order": 90,
        },
        {
            "text": "Выбрать бокс",
            "order": 15,
        },
        {
            "text": "Забрать вещи",
            "order": 20,
        },
        {
            "text": "Своими силами",
            "order": 25,
        },
        {
            "text": "Бесплатная доставка из дома",
            "order": 30,
        },
        {
            "text": "Назад",
            "order": 100,
        },
        {
            "text": "1",
            "order": 50,
        },
        {
            "text": "2",
            "order": 55,
        },
        {
            "text": "3",
            "order": 60,
        }
    ]
    for button in buttons:
        new_button = Button.objects.get(
            text=button['text']
        )
        new_button.order = button['order']
        new_button.save()
    Button.objects.all().order_by('order')


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_auto_20231118_1013'),
    ]

    operations = [
        migrations.RunPython(add_order_to_buttons)
    ]
