# Generated by Django 4.2.7 on 2023-11-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_auto_20231118_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер клиента'),
        ),
    ]
