# Generated by Django 4.2.7 on 2023-11-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес клиента'),
        ),
    ]
