# Generated by Django 4.2.7 on 2023-11-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0025_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='storage.customer', verbose_name='Кому доставлять'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Оформлено'), (2, 'В пути'), (3, 'Доставлено')], null=True, verbose_name='Статус доставки'),
        ),
    ]
