# Generated by Django 4.2.7 on 2023-11-19 12:33

from django.db import migrations


def add_next_step_to_buttons(apps, schema_editor):
    Button = apps.get_model('storage', 'Button')
    Step = apps.get_model('storage', 'Step')
    buttons = [
        {
            "step": "QR-код",
            "text": "Забрать вещи",
        },
    ]
    for button in buttons:
        step = Step.objects.get(name=button['step'])

        new_button = Button.objects.get(
            text=button['text']
        )

        new_button.next_step = step
        new_button.save()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0028_reservation_status'),
    ]

    operations = [
        migrations.RunPython(add_next_step_to_buttons)
    ]
