# Generated by Django 4.2.7 on 2023-11-19 19:39

from django.db import migrations


def fill_up_steps(apps, schema_editor):
    Step = apps.get_model('storage', 'Step')
    steps = [
        {
            "name": "Продление",
            "text": """Укажите количество месяцев для продления
                    """
        },
        {
            "name": "Оплата",
            "text": """Ваша ссылка для оплаты X месяцев хранения
                        (ССЫЛКА)
                        """
        }
    ]
    for step in steps:
        Step.objects.create(
            name=step['name'],
            text=step['text']
        )


def fill_up_buttons(apps, schema_editor):
    Button = apps.get_model('storage', 'Button')
    Step = apps.get_model('storage', 'Step')
    buttons = [
        {
            "step": ["Продление", "Оплата"],
            "text": "Назад",
        },
        {
            "step": ["Продление", "Оплата"],
            "text": "Контакты",
        },
    ]
    for button in buttons:
        steps = [Step.objects.get(name=step) for step in button['step']]

        new_button, is_found = Button.objects.get_or_create(
            text=button['text']
        )
        for step in steps:
            new_button.step.add(step)


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_auto_20231119_2156'),
    ]

    operations = [
        migrations.RunPython(fill_up_steps),
        migrations.RunPython(fill_up_buttons),
    ]
